sudo: required
dist: trusty
language: cpp
cache: ccache

before_install:
  - echo "deb http://packages.matrixlabs.ai/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/matrixio.list
  - sudo apt-get update -qq
  - sudo apt-get install protobuf grpc-trusty --yes --allow-unauthenticated

script:
  - mkdir build
  - cd build && cmake -D CMAKE_CXX_FLAGS="-std=c++11" .. && make
